name: Bug report
description: Create a report to help this extension improve
labels: ['bug']
body:
    - type: textarea
      attributes:
          label: Description
          description: Please provide a concise description of what you're experiencing, what you expected to happen, and any steps to reproduce the behavior.
      validations:
          required: true
    - type: input
      id: extensionVersion
      attributes:
          label: Extension Version
          description: What version of this extension are you using?
          placeholder: 0.8.2
      validations:
          required: true
    - type: textarea
      id: vscode
      attributes:
          label: VS Code Version
          description: |
              What version of VS Code are you using? Copy from:
              On windows: Help -> About
              On mac: Code -> About Visual Studio Code
          placeholder: |
              Version: 1.73.0 (Universal)
              Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
              Date: 2022-11-01T15:38:50.881Z
              Electron: 19.0.17
              Chromium: 102.0.5005.167
              Node.js: 16.14.2
              V8: 10.2.154.15-electron.0
              OS: Darwin x64 22.1.0
              Sandboxed: No
      validations:
          required: true
    - type: textarea
      id: settings
      attributes:
          label: Extension Settings
          description: How do you config the extension?
          placeholder: |
              ```jsonc
              {
                  "openInExternalApp.openMapper": [
                      {
                          "extensionName": "html",
                          "apps": [
                              {
                                  "title": "chrome",
                                  "openCommand": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
                              }
                          ]
                      }
              }
              ```
      validations:
          required: true
    - type: textarea
      attributes:
          label: Logs, Screenshots, Screen Recording etc
          description: You can open the output panel and select "Open in External App" channel to check extension logs
      validations:
          required: false
